[agent][observium] Skip measurements with None value
anodot/daria pull request #364
Opened 2022-03-11 16:16 UTC by vpoliukh

- Skip `None` measurements
- Update tests

Related ticket: [AL-10834](https://anodot.atlassian.net/browse/AL-10834)

2022-03-14 16:11 UTC, AntonZelenin requested changes

2022-03-15 10:20 UTC, vpoliukh commented on agent/src/agent/data_extractor/observium/observium.py
> +            metric['measurements'] = {k: v for k, v in metric['measurements'].items() if v is not None}
Added skip_none: bool option

2022-03-15 10:40 UTC, AntonZelenin approved these changes

2022-03-15 15:02 UTC, dariakharlan approved these changes

2022-03-15 15:02 UTC, merged