[api][pipeline] Elastic query when creating pipeline with API
anodot/daria pull request #368
Opened 2022-03-21 22:59 UTC by vpoliukh

- Send query with the request body when creating pipeline with API
- Update elastic source `validate_connection`

Related ticket: [AL-10746](https://anodot.atlassian.net/browse/AL-10746)

2022-03-23 14:28 UTC, AntonZelenin commented on agent/src/agent/source/validator.py
> -        super().validate_connection()
please use the validation that existed before

2022-03-25 10:36 UTC, AntonZelenin approved these changes

2022-03-25 13:12 UTC, dariakharlan requested changes
Please also add to the api docs (agent/api/docs) an example of how to use a query parameter and  to our main wiki page

2022-03-28 08:13 UTC, dariakharlan approved these changes

2022-03-28 08:13 UTC, merged