[agent][cli] Fix CLI error messages
anodot/daria pull request #373
Opened 2022-03-29 22:53 UTC by vpoliukh

- Add exception handling for source does not exist cases
- Add exception handling for pipeline does not exist cases
- Add the missing description for `agent pipeline ...` commands

Related ticket: [AL-10472](https://anodot.atlassian.net/browse/AL-10472)

2022-03-31 15:42 UTC, AntonZelenin approved these changes

2022-04-04 08:21 UTC, AntonZelenin approved these changes

2022-04-04 14:54 UTC, dariakharlan requested changes

2022-04-04 14:54 UTC, dariakharlan commented on agent/src/agent/modules/logger.py
> +        handler.setLevel(logging.ERROR)
setting global level error is unnecessary. it means that log will show only error messages, but info messages are also fine

2022-04-04 14:54 UTC, dariakharlan commented on agent/src/agent/pipeline/json_builder/json_builder.py
> +            logger_.debug(e, exc_info=True)
this is error so it should be `logger_.error(e, exc_info=True)`. Same for others

2022-04-05 13:12 UTC, merged