[agent][victoria] Add DVP config support
anodot/daria pull request #374
Opened 2022-03-30 21:33 UTC by vpoliukh

- Send `last_timestamp` as watermark if no data and `DVP_ENABLED`

Related ticket: [AL-11040](https://anodot.atlassian.net/browse/AL-11040)

2022-03-31 15:51 UTC, AntonZelenin requested changes

2022-03-31 15:51 UTC, AntonZelenin commented on agent/tests/test_pipelines/test_promql_http.py
> +                'sleep': 15
it's 15 seconds by default

2022-03-31 15:51 UTC, AntonZelenin commented on agent/src/agent/pipeline/config/jython_scripts/promql.py
> +    if result_['data']['result']:
I guess you can move this check to the main function because they're the same here and in the `process_vector`

2022-03-31 20:22 UTC, vpoliukh commented on agent/src/agent/pipeline/config/jython_scripts/promql.py
> +                # records with last_timestamp only
Agree, missed that:( 
Updated again. Now `process_matrix` and `process_vector` are left untouched and added separate batch for 'no data' case

2022-03-31 20:27 UTC, AntonZelenin approved these changes

2022-04-01 08:39 UTC, dariakharlan approved these changes

2022-04-01 08:39 UTC, merged