[agent] Update retry policy for RUNNING_ERROR cases
anodot/daria pull request #382
Opened 2022-04-12 16:44 UTC by vpoliukh

- Set pipelines retry attempts in case of RUNNING_ERROR to infinity
- Added `notification_sent` flag to `pipeline_retries` table to avoid sending notification when **send_to_bc.py** called every 1 minute and  pipeline try to start every 5 minutes
- Added separate cron script to reset `number_of_error_statuses` counter and `notification_sent` flag

Related ticket: [AL-10986](https://anodot.atlassian.net/browse/AL-10986)

2022-04-13 15:13 UTC, AntonZelenin requested changes

2022-04-13 15:13 UTC, AntonZelenin commented on agent/src/agent/pipeline/manager.py
> +           and pipeline_.retries.number_of_error_statuses - 1 == constants.STREAMSETS_NOTIFY_AFTER_RETRY_ATTEMPTS \
`>=` just in case there're more retries for some reason

2022-04-13 15:13 UTC, AntonZelenin commented on agent/src/agent/pipeline/manager.py
> +        set_pipeline_retries_notification_sent(pipeline_, False)
I think if we reset pipeline retries, we should always reset notification as well, if so, you can put this call inside `reset_pipeline_retries`

2022-04-13 15:13 UTC, AntonZelenin commented on agent/src/agent/pipeline/manager.py
> +    if not pipeline_.retries:
I think it should not be possible to call this method when retries don't exist, so this check is probably not needed
Or at least you don't need to create retries if they don't exist

2022-04-15 21:23 UTC, vpoliukh commented on agent/src/agent/scripts/reset_retry_counters.py
> +        try:
Skipped pipeline_ with retries as None

2022-04-15 22:15 UTC, AntonZelenin approved these changes

2022-04-21 11:31 UTC, dariakharlan approved these changes

2022-04-21 11:31 UTC, merged