Al 11997 add kafka source
anodot/daria pull request #454
Opened 2022-09-05 15:31 UTC by AlexMuliar

2022-09-06 13:22 UTC, vpoliukh commented on agent/src/agent/pipeline/config/base_pipelines/raw/kafka_http.json
> +      "instanceName" : "KafkaMultitopicConsumer_01",
"instanceName" : "source"

2022-09-07 09:12 UTC, vpoliukh commented on agent/src/agent/pipeline/json_builder/__init__.py
> +        source.TYPE_KAFKA: KafkaBuilder,
Isn't that the `KafkaRawBuilder` needed to be here? If not, then `KafkaRawBuilder` seems not used

2022-09-07 09:53 UTC, vpoliukh approved these changes

2022-09-07 13:22 UTC, dariakharlan requested changes

2022-09-07 13:22 UTC, dariakharlan commented on agent/src/agent/pipeline/json_builder/json_schema_definitions/raw/kafka.json
> +  "required": ["values", "dimensions", "timestamp"]
in raw pipeline we don't need to specify these because we don't do any data transformations

2022-09-07 13:22 UTC, dariakharlan commented on agent/tests/test_raw/test_input/test_kafka.py
> +        'test_create_raw_with_file': [{'file_name': 'raw/pipelines/kafka'}],
please also add a test for csv output format

2022-09-13 09:21 UTC, dariakharlan approved these changes

2022-09-13 09:21 UTC, merged