AL-12024: Create jdbc event pipeline
anodot/daria pull request #459
Opened 2022-09-19 09:05 UTC by AlexMuliar

2022-09-21 11:07 UTC, dariakharlan requested changes

2022-09-21 11:07 UTC, dariakharlan commented on agent/src/agent/pipeline/config/loader.py
> +            source.TYPE_POSTGRES: 'jdbc.json',
Missing TYPE_ORACLE

2022-09-22 08:30 UTC, vpoliukh commented on agent/tests/test_pipelines/test_2/test_mysql_http.py
> +            # {'name': 'test_events_jdbc', 'output': 'events_jdbc.json', 'pipeline_type': 'mysql'},
So, we do not check the expected output?

2022-09-22 08:30 UTC, vpoliukh commented on agent/tests/test_input/test_2/test_mysql_http.py
> +        super(TestMySQL, self)._test_create_with_file(cli_runner, file_name, override_config, cli.pipeline.create_events)
Why do you prefer `super(TestMySQL, self)._test_create_with_file`?
Because there is no overriding, you can call just `self._test_create_with_file()`

2022-09-22 08:30 UTC, vpoliukh commented on agent/src/agent/pipeline/manager.py
> +        offset = '{}'
Could you please explain why we need this instead of a `return` before?

2022-09-22 08:30 UTC, vpoliukh commented on agent/src/agent/pipeline/config/jython_scripts/events_destination.py
> +        send_offset(record.value['offset'])
Just to be sure, if inside `send_event` function `client.send_events` will fail to send with some exception, we still perform `send_offset` after it, right?

2022-09-22 12:52 UTC, vpoliukh commented on agent/src/agent/pipeline/config/jython_scripts/events_destination.py
> +        sdc.error.write(str(e))
If I'm not mistaken, `sdc.error` takes two arguments: record and some message.
If you want just log the error, the `sdc.log.error` should be used
[Here](https://docs.streamsets.com/datacollector/latest/help/datacollector/UserGuide/Processors/Jython.html?hl=sdc.error) is a docs

2022-09-23 08:26 UTC, vpoliukh approved these changes

2022-09-26 11:26 UTC, dariakharlan approved these changes

2022-09-26 11:26 UTC, merged