AL-12097: create or update transform file on agent apply
anodot/daria pull request #475
Opened 2022-11-03 14:26 UTC by AlexMuliar

2022-11-07 11:59 UTC, vpoliukh requested changes

2022-11-07 11:59 UTC, vpoliukh commented on agent/src/agent/cli/apply.py
> +                    f.write(config['transform']['config'])
Need to check that 'file' key in config['transform'], will be an exception if transform declared without file.
Sees snmp_table pipeline for example

2022-11-09 08:01 UTC, dariakharlan commented
In the ticket I wrote ```export csv config with pipelines to a file (configs like transform files etc)``` it's not implemented here. I meant to export the transform file (for some pipelines it can be also a query file) with config when we do `agent pipeline export`. Let me know if I need to explain it more

2022-11-09 08:03 UTC, dariakharlan requested changes
In the ticket I wrote ```export csv config with pipelines to a file (configs like transform files etc)```, it means exporting the transform file (for some pipelines it can be also a query file) with config when we do `agent pipeline export`. It's not implemented here, let me know if I need to explain more

2022-11-11 12:29 UTC, dariakharlan requested changes

2022-11-11 12:29 UTC, dariakharlan commented on agent/src/agent/cli/pipeline.py
> +    def _export_file(path, pipeline_name):
the file might not exist anymore inside the container (for example if the container is recreated) you need to copy the content of the file from the config that is stored in the dataabse

2022-11-11 12:29 UTC, dariakharlan commented on agent/src/agent/cli/pipeline.py
> +        destination = os.path.join(os.path.dirname(dir_path), 'processing_files', pipeline_name)
the file name should be the same as original value, destination path is the same dir

2022-11-18 15:09 UTC, dariakharlan approved these changes

2022-11-18 15:09 UTC, merged